# Specify a base image
FROM node:alpine

WORKDIR '/app'

ENV PATH /app/node_modules/.bin:$PATH

# Install some depenendencies and run all test
COPY package.json .
RUN yarn install 
COPY . .
RUN yarn test-prod


# Uses port which is used by the actual application
EXPOSE 3000

# Default command
CMD ["yarn", "run", "start"]
